language: python
sudo: false

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /docs/`
- py.test --pyargs AFQ --cov-report term-missing --cov=AFQ

after_success:
- coveralls
